### ISSUE TITLE
Survival way to gain Mana

### ISSUE THREAD

**Issue by Max094Reikeb** [Max094Reikeb/ArcaneCraft-II#10]
Yet, there's no survival way to add Mana. There should be...

Additional idea: add new plant(s) that once harvested, drop Mana that the player can collect.

**Comment by MrCreeps** [comment]
Once killing mobs there is a small chance that they drop mana orbs (the one that Fred textured) and these restore the mana.

**Comment by Max094Reikeb** [comment]
> Once killing mobs there is a small chance that they drop mana orbs (the one that Fred textured) and these restore the mana.

Why would that be a thing? Mobs already drop XP...
