### ISSUE TITLE
[BUG] Arcanecraft II mod not working on server?

### ISSUE THREAD

**Issue by Jolteon1234amongus** [Max094Reikeb/ArcaneCraft-II#21]
I have some other mods but only arcanecraft II is erroring for some reason? Idk why
https://www.toptal.com/developers/hastebin/rixizesopo.yaml --log

 - ArcaneCraft2-beta-v3
 - 1.16.5
 - Forge-1.16.5-36.2.28

**Comment by Max094Reikeb** [comment]
First of all, 1.16.5 is deprecated version. Because the mod is in beta, there will be plenty of new stuff in 1.17.1.
Then, I don't know if this error happens in 1.17.1. If this bug even get fixed, it won't be for 1.16.5 version so I advise you to update your server.

**Comment by Max094Reikeb** [comment]
Ok so I tested with latest version of the mod in 1.17.1 and it works fine on a server.
